### ISSUE TITLE
@griffm, Are you  griffm of CodePlex's FO.NET ?

### ISSUE THREAD

**Issue by prepare** [prepare/FO.NET#1]
Hello, @griffm,

Are you  [griffm](http://www.codeplex.com/site/users/view/griffm) of CodePlex's FO.NET ? 

I want to say "_THANK YOU_" for your software 
and make a reference  to the original creator of FO.NET project.

**Comment by griffm** [comment]
Hey, just spotted this message. Yes, I was part of the team of 2 who ported FOP to C# and created FO.NET (originally called Apoc XSL-FO). So glad that people are still enjoying and benefiting from it :)
